### ISSUE TITLE
部署到Vercel中的提示页面找不到

### ISSUE THREAD

**Issue by taurus2146** [TobeBetterV/Moments#2]
![image](https://github.com/user-attachments/assets/47c8395b-cf44-4c8e-97eb-c8dd49d701d6)
默认进入之后不会跳转到/notes页面 导致提示页面找不到

**Comment by taurus2146** [comment]
我在next.config.mjs修改了重定向那儿的部分代码,由原先的
try {
      return [...redirects, ...(await get("redirects"))];
    } catch {
      return [];
    }
  }修改为
  try {
      return [...redirects, ...(await get("redirects"))];
    } catch {
      return [{
        source: "/",
        destination: "/notes",
        permanent: true,
      }];
    }
  }就正常可以跳转了

**Comment by taurus2146** [comment]
不过如果一条笔记都没有的时候,笔记列表那儿会显示加载失败
![image](https://github.com/user-attachments/assets/379575bf-256d-4fc5-8efe-46f111cc82ab)

**Comment by TobeBetterV** [comment]
感谢，我修一下。

**Comment by TobeBetterV** [comment]
fixed in https://github.com/TobeBetterV/Moments/commit/b47d3bb6420db8b604965a849d54b1696741ab8e
